site_name: hansmolemanpng
site_description: Security research and offensive security notes
site_url: https://hansmolemanpng.github.io

  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.high

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
